name: Caller CI/CD Release

on:
 push:
  branches:
   - main
   - "release/*"
 workflow_dispatch:
  inputs:
   action:
    description: "Selecione o fluxo desejado:"
    required: true
    default: "Build & Deploy HOM"
    type: choice
    options:
     - "Build Only"
     - "Build & Deploy HOM"
     - "Build & Deploy PROD"
   enable_sonar:
    description: "Habilitar análise do SonarQube?"
    required: false
    type: boolean
    default: true

jobs:
 call-reusable-release:
  uses: Integra-Mobilidade/reusable-workflows/.github/workflows/nestjs-release.yml@main
  with:
   action: ${{ inputs.action || 'Build & Deploy HOM' }}
   enable_sonar: ${{ inputs.enable_sonar != false }}
  secrets: inherit
