name: Caller CI/CD Sandbox

on:
 push:
  branches:
   - develop
 workflow_dispatch:
  inputs:
   action:
    description: "O que deseja fazer?"
    required: true
    default: "Build & Deploy"
    type: choice
    options:
     - "Build Only"
     - "Build & Deploy"
   enable_sonar:
    description: "Habilitar análise do SonarQube?"
    required: false
    type: boolean
    default: true

jobs:
 call-reusable-sandbox:
  uses: Integra-Mobilidade/reusable-workflows/.github/workflows/nestjs-sandbox.yml@main
  with:
   action: ${{ inputs.action || 'Build & Deploy' }}
   enable_sonar: ${{ inputs.enable_sonar != false }}
  secrets: inherit
