name: Caller Pull Request Check

on:
 pull_request:
  types: [opened, synchronize, reopened]
  branches: ["main", "develop"]

jobs:
 call-reusable-pr-check:
  uses: Integra-Mobilidade/reusable-workflows/.github/workflows/nestjs-pr-check.yml@main
  secrets: inherit
